### ISSUE TITLE
Provide Access to Latest TCGA Data

### ISSUE THREAD

**Issue by DarioS** [waldronlab/curatedTCGAData#10]
The data available is preprocessed before the mid-2016 harmonisation, which uses a newer reference genome and different analytic algorithms. Also, the Genomic Data Commons data has had some substantial changes since last year. For example, four months ago, the [mutation data was reprocessed](https://docs.gdc.cancer.gov/Data/Release_Notes/Data_Release_Notes/#data-release-70) to remove Oxo-G artefacts caused by the exome-seq kit.

**Comment by lwaldron** [comment]
This is a good comment and a worthwhile change. Unfortunately I expect it will take a while to be able to migrate the underlying downloader from RTCGAToolbox to the GenomicDataCommons library, assuming there will be a different set of quirks and inconsistencies that come up when integrating the data. @LiNk-NY have you tried out just using Sean's GenomicDataCommons library (I mean just basic use, not as the curatedTCGAData downloader)?

**Comment by LiNk-NY** [comment]
I haven't really tried to download a whole set of MultiAssayExperiment datasets but I can see what the package has to offer.

**Comment by LiNk-NY** [comment]
This issue is outside the scope of the package as it is currently. We'd have to write an interface to `GenomicDataCommons` and avoid conflating the two data sources.
