### ISSUE TITLE
Vignette Loading Library MultiAssayExperiment

### ISSUE THREAD

**Issue by DarioS** [waldronlab/curatedTCGAData#11]
In the vignette, the preparation section has 

```
library(curatedTCGAData)
library(MultiAssayExperiment)
```

but the second package load is redundant because curatedTCGAData depends on MultiAssayExperiment.

**Comment by LiNk-NY** [comment]
Thanks for the review. This is mostly for raising `MultiAssayExperiment` dependency awareness.
