### ISSUE TITLE
Temporary Data Stored Inside User's Home Directory

### ISSUE THREAD

**Issue by DarioS** [waldronlab/curatedTCGAData#12]
Temporary files downloaded to the user's computer are stored in `/home/userName/.ExperimentHub/folderID`. Typically, user home directories on a department's server have disk quotas enforced. Perhaps this data folder should be defined by R's `tempdir()` command instead? Folders in `/tmp/`often don't have disk quotas and are automatically deleted when the time is right.

**Comment by lwaldron** [comment]
This could be addressed by exposing the `ExperimentHub::ExperimentHub()` extra arguments through `curatedTCGAData()`, which include an option to specify cache location.
