### ISSUE TITLE
Viewing Clinical Data Floods Console With Text

### ISSUE THREAD

**Issue by DarioS** [waldronlab/curatedTCGAData#13]
I am looking at clinical data for melanoma, but there's too much of it.

```r
melanomaMicroRNA <- curatedTCGAData(diseaseCode = "SKCM", assays = "miRNASeqGene", dry.run = FALSE)
head(colData(melanomaMicroRNA))
```

Results in a lot of text being printed, ending with `[ reached getOption("max.print") -- omitted 7 rows ]`.

Similarly, `colnames(colData(melanomaMicroRNA))` ends with `[ reached getOption("max.print") -- omitted 534 entries ]`.

Perhaps providing an option to just store some of the main clinical variables would make the table easier to work with.

**Comment by lwaldron** [comment]
I actually discussed this with @vjcitn recently - I think the gist of our conversation was that `DataFrame` itself could use a better show method for when there are lots of columns. In the meantime, you could identify the columns to the ones you most likely want with the `getClinicalNames()` function from [waldronlab/TCGAutils](github.com/waldronlab/TCGAutils) repo, and subset the `colData` to only these.

**Comment by LiNk-NY** [comment]
This is more of an issue for `S4Vectors::DataFrame`..
