### ISSUE TITLE
two BRCA methylation datasets?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedTCGAData#22]
Why are there `BRCA_Methylation1` and `BRCA_Methylation2`? Presumably it's because these datasets are large, but when moving to HDF5 there's no reason to have them separate. (excerpted below)

```
> library(curatedTCGAData) 
> curatedTCGAData("BRCA")                                  
                         BRCA_Methylation1 
"BRCA_Methylation_methyl27-20160128.rda" 

                           BRCA_Methylation2
   "BRCA_Methylation_methyl450-20160128.rda"
```

**Comment by lwaldron** [comment]
Sorry, I remember that these should get joined upon MAE serialization. I'm in the process of doing that, will close the issue as soon as I see they are joined.

**Comment by LiNk-NY** [comment]
Hi Levi, @lwaldron 
These are two different methylation assays with the 27K and 450K target regions.
