### ISSUE TITLE
exportClass() no longer supported?

### ISSUE THREAD

**Issue by michaelSkaro** [waldronlab/curatedTCGAData#37]
Hello, on the HTML link in the bioconductor web address an eportClass() function is demonstrated under section 3.2. I have reproduced your session and don't think I am missing any packages(but could definitely be wrong). I looked through your package source and did not see the function. Is this utility no longer supported or am I missing another package to handle this task?

**Comment by LiNk-NY** [comment]
Hi @michaelSkaro 
That function is a method in `MultiAssayExperiment`.
You shouldn't be missing that package as `curatedTCGAData` depends on it. 
Please make sure you are not mixing versions and are using `BiocManager::valid()`
to check your installation.

**Comment by michaelSkaro** [comment]
Thanks for your time I had 1 or 2 packages that were out of date. Following the update I was able to use the exportClass() function. 

Regards,

MS
