### ISSUE TITLE
Position of new 'version' argument to curatedTCGAData()

### ISSUE THREAD

**Issue by hpages** [waldronlab/curatedTCGAData#44]
Hi Marcel,

The addition of the `version` argument to the `curatedTCGAData()` interface (commit
5e328b84dc0be5c06c38c05222085c2dad9ae29b) breaks packages AMARETTO and BiocOncoTK:

- https://bioconductor.org/checkResults/3.13/bioc-LATEST/AMARETTO/malbec2-checksrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/BiocOncoTK/malbec2-checksrc.html

Have you considered adding the new argument **after** the existing arguments (and before the ellipsis), and also to give it a default value (`"1.1.38"`)? This would make the change backward compatible.

H.

**Comment by LiNk-NY** [comment]
Hi Hervé, 
Thanks for looking into this. 
I have posted PRs some time ago for in the respective repositories: 
https://github.com/gevaertlab/AMARETTO/pull/14
https://github.com/vjcitn/BiocOncoTK/pull/1

Yes, I did consider that and I wanted maintainers and users to be aware of the new version forcing them to make a choice. 
Best,
Marcel

**Comment by hpages** [comment]
I see. All is good then. Thanks!
