### ISSUE TITLE
Methylation data platform

### ISSUE THREAD

**Issue by fedenichetti** [waldronlab/curatedTCGAData#49]
Hi there, one simple question on methylation data downloaded from the package: 

some tumor types have only one Methylation file without a specified platform (e.g. PAAD has only PAAD_Methylation-20160128), while others (like LUAD) have more than one (e.g.  LUAD_Methylation_methyl27-20160128 and LUAD_Methylation_methyl450-20160128).

In cases like PAAD, which one should I assume it to be, 450 or 27? 

Thanks!

**Comment by LiNk-NY** [comment]
Hi Federico, @fedenichetti 

The data from `curatedTCGAData` is based on the outputs of `RTCGAToolbox`.
The `getLinks` function will show data files. It seems like these file names were
lost somewhere along the pipeline and should be included in the metadata. 

```r
> RTCGAToolbox::getLinks("PAAD", Methylation=TRUE)
                                                                                                                                                              href 
"gdac.broadinstitute.org_PAAD.Merge_methylation__humanmethylation450__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2016012800.0.0.tar.gz" 
```

**Comment by fedenichetti** [comment]
Many thanks!
