### ISSUE TITLE
RNASeq2Gene values

### ISSUE THREAD

**Issue by nargessn** [waldronlab/curatedTCGAData#54]
Hi and thanks for the very practical package. 

I have been using it to download RNAseq2Gene values for some TCGA cohorts. Based on the manual, this should include RSEM TPM values. With TPM, I would expect library sizes to add up to 1 million per sample but this is not the case for dataset I checked (SKCM). Does RNAseq2Gene implies something else or am I somehow misunderstood here?

Thanks for the help in advance!
Narges

**Comment by LiNk-NY** [comment]
See #53
